### PR TITLE
Setup CI pipeline to automate unittests

### PR DESCRIPTION
**Pull request by rudyeila**
Add CI configuration that automatically runs the unit tests using pytest

### CODE REVIEW

**Review by NaseemSrour — COMMENTED** [review]
What's this?
The tests are run on GitHub?!

**Comment by rudyeila** [comment]
That's the idea yes, once it is set up properly. Lets merge it and see if it works.

**Comment by NaseemSrour** [comment]
Ok let's add it.
I'm gonna need to read more about the Github Actions though.

**Review by NaseemSrour — APPROVED** [review]
Looks good as first preparation for CI.

**Pull request merged**
