### PR TITLE
Fix/GitHub flow

### PR DESCRIPTION
**Pull request by rudyeila**
Now having merged the tests with the dev branch, I was able to test the automatic pytest action on Github. There were some issues that I fixed:
- made sure the correct requirements.txt file is being detected (inside the server folder)
- the tests are now only ran with python3.9, as older version have some compatibility issues with typing
- the flow will now trigger the unit tests when pushing to any branch, not only dev

Go to the "[Actions](https://github.com/NaseemSrour/Deliveries/actions)" tab to see some example output

### CODE REVIEW

**Comment by NaseemSrour** [comment]
This seems interesting!
So on every pull request to 'dev' the test will be triggered?
If yes, this way we can build our tests in Python (PyTest), and have them automatically executed in GitHub Actions when we create a pull request??

**Review by NaseemSrour — COMMENTED** [review]
Seems helpful, definitely gonna try that when I create a test for DBItem.

**Review by NaseemSrour — APPROVED** [review]
Forgot to click Approve.

**Comment by rudyeila** [comment]
The tests, i.e. the "pytest -v" command should be executed everytime you push to ANY branch. 
Right now the tests will also be executed when you make a pull request to dev.

**Pull request merged**
