### PR TITLE
Rudy/setup server

### PR DESCRIPTION
**Pull request by rudyeila**
Setup a basic server...

@NaseemSrour, I wasn't able to take your code exactöy, because the whole DB logic will be refactored out. So I just setup an example for the Item resource and left Todo comments for when the DB controller is ready.

### CODE REVIEW

**Review by NaseemSrour — APPROVED** [review]
Awesome, looks good and ready.

**Review by majdya — APPROVED** [review]
Clean, nice.

**Comment by NaseemSrour** [comment]
@rudyeila can you explain what an endpoint argument does? The docs aren't very clear about it.

**Comment by rudyeila** [comment]
> @rudyeila can you explain what an endpoint argument does? The docs aren't very clear about it.

I am not sure either 😅 it's left over from copy pasting

**Pull request merged**
